### ISSUE TITLE
Why do you need proto files in client side? 

### ISSUE THREAD

**Issue by R-Miner** [shygiants/tf-serving-nodejs-client#1]
@shygiants 

I successfully generated a python-python client-server tensorflow servings procedure. Now I am trying to develop a C3-python client-server with tensorflow serving, with a C# client that runs in windows with no python installed it that machine. 

My question is why I need the proto file in the client side when using gRPC. The whole purpose is to send the model, version of the model and the image for the server to do the predication and send back the result right?

rather 
Why a gRPC client needs  proto files?

Any help is appreciated!

**Comment by shygiants** [comment]
As I know, gRPC client needs to know about the service, which is defined on proto file. Actually, the model name, version of the model and the image is defined on proto files.
https://github.com/shygiants/tf-serving-nodejs-client/blob/703bf5fb13fd0f81235d7bade7fe11c7fa7ae030/protos/predict.proto#L12-L22

https://github.com/shygiants/tf-serving-nodejs-client/blob/703bf5fb13fd0f81235d7bade7fe11c7fa7ae030/protos/model.proto#L9-L22

Somewhere in gRPC's documentation says as following
> With gRPC we can define our service once in a .proto file and implement clients and servers in any of gRPC’s supported languages,...

And, you can find that gRPC client loads a proto file from the code
https://github.com/shygiants/tf-serving-nodejs-client/blob/703bf5fb13fd0f81235d7bade7fe11c7fa7ae030/src/index.js#L14

I hope it helps!
